const statefullWebRedux = (name, ext = 'css') => [
  `import React, { Component } from 'react'`,
  "import PropTypes from 'prop-types'",
  "import { connect } from 'react-redux'",
  "// import { get } from 'lodash'",
  "",
  "// import actions from 'actions'",
  `import styles from './${name}.${ext}'`,
  "",
  `class ${name} extends Component {`,
  "  static propTypes = {}",
  "",
  "  render = () => {",
  "    return (",
  `      <div className={styles.${name}}>`,
  `        <span>${name} statefull component</span>`,
  "      </div>",
  "    )",
  "  }",
  "}",
  "",
  "const mapStateToProps = () => ({})",
  "",
  "const mapDispatchToProps = dispatch => ({})",
  "",
  `export default connect(mapStateToProps, mapDispatchToProps)(${name})`,
].join('\n')

const statefullWeb = (name, ext = 'css') => [
  `import React, { Component } from 'react'`,
  "import PropTypes from 'prop-types'",
  "",
  `import styles from './${name}.${ext}'`,
  "",
  `class ${name} extends Component {`,
  "  static propTypes = {}",
  "",
  "  render = () => {",
  "    return (",
  `      <div className={styles.${name}}>`,
  `        <span>${name} statefull component</span>`,
  "      </div>",
  "    )",
  "  }",
  "}",
  "",
  `export default ${name}`,
].join('\n')

module.exports = {
  statefullWebRedux,
  statefullWeb,
}
